unit TestUniqId;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,

  uDBUtils;

type
  TTestUniqId = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestMethod;
  end;

implementation

procedure TTestUniqId.SetUp;
begin
end;

procedure TTestUniqId.TearDown;
begin
end;

procedure TTestUniqId.TestMethod;
begin
  //
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TTestUniqId.Suite);
end.

